global ...
...
FileName FilePath...
TestType...
TotalDisp TotalTime TimeIncr...
IncrDisp...
PlaneStress PlaneStrain...
NumOfPhase TypeOfPhase ...
MatIndex MatType MatSet...
ECount VECount...
NumOfInterphase IntType...
VECNo...
...
ElasticModulus EPoissonRatio...
...
VENumPronySeries VEPronySeries VEPronySeriesInf VEPoissonRatio ...
...
VECZNumPronySeries VECZPronySeries VECZPronySeriesInf ...
SigmaN SigmaT DeltaN DeltaT...
PLc PLm PLn...
ConA ConM ConLambdabar ConDelta ... 
...
NumNodes NumEl NumIntEl...
NF NDBC Coo Con NDISP NDOF DINC IntEl BandWidth...
TIMESTEP NumTimeStep ...
...
LimXY  LimStress RecomLim NumSpec ...
StressContourIndex StepJump FrameDim ...
FlagGraphSig ...
DamageModel ...
FramePerSec ...
...
NN NEL NNPEREL...





 



