%    MIDAS-VT-Pre Copyright (C) 2018  Keyvan Zare-Rami
%
%    This program is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.
%
%    This program is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with this program.  If not, see <https://www.gnu.org/licenses/>.

global ...
...
FileName FilePath...
TestType...
TotalDisp TotalTime TimeIncr...
IncrDisp...
PlaneStress PlaneStrain...
NumOfPhase TypeOfPhase ...
MatIndex MatType MatSet...
ECount VECount...
NumOfInterphase IntType...
VECNo...
...
ElasticModulus EPoissonRatio...
...
VENumPronySeries VEPronySeries VEPronySeriesInf VEPoissonRatio ...
...
VECZNumPronySeries VECZPronySeries VECZPronySeriesInf ...
SigmaN SigmaT DeltaN DeltaT...
PLc PLm PLn...
ConA ConM ConLambdabar ConDelta ... 
...
NumNodes NumEl NumIntEl...
NF NDBC Coo Con NDISP NDOF DINC IntEl BandWidth...
TIMESTEP NumTimeStep ...
...
plotGraph_XAxisIndex plotGraph_YAxisIndex ...
...
LimXY  LimStress RecomLim NumSpec ...
StressContourIndex StepJump FrameDim ...
FlagGraphSig ...
DamageModel ...
FramePerSec ...
...
...
plotContourIndex...
plotTargetStep...
...
NN NEL NNPEREL...





 



