%    MIDAS-VT-Pre Copyright (C) 2018  Keyvan Zare-Rami
%
%    This program is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.
%
%    This program is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with this program.  If not, see <https://www.gnu.org/licenses/>.

global ...
... GUI_Start_Preprocessor
ModelGenModeIndex...
...MAIN1
EnableCohELIndex...
...Image2Shape
BoundXY...
...Shape2GEom
dl ...
...Geom2Mesh
Coo_O Con_O NumRegEl El_Phase1 El_Phase2 El_CZ ...
... AddCohEl
CohEl_Phase1 CohEl_Phase2 CohEl_InterPhase12...
... Geometry
TestType... 
TT_w TT_h TT_CZw TT_CZh...
TPBT_w TPBT_h TPBT_a TPBT_nl TPBT_nw TPBT_CZw TPBT_CZh ...
SCBT_w SCBT_a SCBT_nl SCBT_nw SCBT_CZw SCBT_CZh...
... Microstructure
HeteroIndex...
MixtureImageName MixtureImagePath...
MinFineParticleSize...
...Mesh
JigglingIndex MaxMeshSize MeshGrowthRate JigglingMaxIter...
... Boundary Condition
TT_T TT_B TT_L...
TPBT_LS TPBT_RS TPBT_LP...
SCBT_LS SCBT_RS SCBT_LP...
...RCM
BandWidth...
...GUI MAIN 2
FileName_1 FilePath_1...
FileName_2 FilePath_2...
FileName_3 FilePath_3...
FileName_4 FilePath_4...
FileName_5 FilePath_5...
FileName_6 FilePath_6 ...
... Write Output
OutputFileName
